INSERT INTO users (name, age) VALUES ("Susan", 18);
INSERT INTO users (name, age) VALUES ("Su", 12);
INSERT INTO users (name, age) VALUES ("Ryan", 25);
INSERT INTO users (name, age) VALUES ("David", 21);
INSERT INTO users (name, age) VALUES ("Mike", 30);
INSERT INTO users (name, age) VALUES ("Terrence", 26);
INSERT INTO users (name, age) VALUES ("Gma", 70);
INSERT INTO users (name, age) VALUES ("TJ", 18);
INSERT INTO users (name, age) VALUES ("Esme", 35);
INSERT INTO users (name, age) VALUES ("Uly", 48);
INSERT INTO users (name, age) VALUES ("Josh", 36);
INSERT INTO users (name, age) VALUES ("Jacob", 58);
INSERT INTO users (name, age) VALUES ("Eli", 25);
INSERT INTO users (name, age) VALUES ("Begnaud", 82);
INSERT INTO users (name, age) VALUES ("Soccer", 12);
INSERT INTO users (name, age) VALUES ("Alex", 40);
INSERT INTO users (name, age) VALUES ("Log", 19);
INSERT INTO users (name, age) VALUES ("Locker", 29);
INSERT INTO users (name, age) VALUES ("Alan", 21);
INSERT INTO users (name, age) VALUES ("Apple", 1);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Soccer Shoe", "Sports", 1000, "4/21/2020", "9/1/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Stilts", "Growth", 5000, "6/21/2020", "12/1/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Need Some Food", "Food", 100, "7/2/2020", "11/1/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Video Game", "Games", 10000, "6/13/2020", "2/1/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Science Project", "Science", 200, "1/10/2020", "5/6/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("School Dance Program", "Dance", 20000, "8/7/2020", "11/13/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Computer", "Tech", 1000, "8/25/2020", "10/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Trip to Italy", "Travel", 5000, "10/14/2020", "12/26/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Brilliant app idea", "Tech", 100000, "9/21/2020", "5/17/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Modern Oven", "Tech", 2000, "7/4/2020", "8/17/2020");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (106, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 9, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 11, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1007, 11, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 12, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (507, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 15, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 17, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 18, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 19, 1);